version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - BASE_URL=http://localhost:8080
      - CODE_LENGTH=6
      - GIN_MODE=release
    restart: unless-stopped
